"use client";
import Image from 'next/image'
import type { Metadata } from 'next'
import { getVehichles } from '@/app/(api)/services/vehicle'
import { useEffect } from 'react';


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Home() {

  useEffect(() => {
    (async() => {
      await getVehichles();

    })();

  }, [])

  //console.log(vehicles)

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      
    </main>
  )
}
